apiVersion: apps/v1
kind: Deployment

metadata:
  name: any-name

spec:
  selector:
    matchLabels:
      app: mahmoud
  replicas: 3
  template:
    metadata:
      name: my-first-pod
      labels:
        app: mahmoud
    spec:
      containers:
        - image: nginx:alpine
          name: nginx-container
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "100Mi"